stages:
  - test
  - deploy
test:
  stage: test
  script:
    - tox
  tags:
    - python2
deploy_n3:
  stage: deploy
  before_script:
    - exit 0
  after_script:
    - exit 0
  script:
    - exit 0
  only:
    - master
